### ISSUE TITLE
certificates in source?

### ISSUE THREAD

**Issue by fubar2** [ARTbio/galaxyXpand#18]
Is [this (and the other certificates)](https://github.com/fubar2/galaxyXpand/blob/main/environments/Conect/files/ssl/usegalaxy_sorbonne-universite_fr_bundle.crt) a good thing to have outside your ansible .vault file ? It may not matter but gitguardian complained about my fork :)

**Comment by drosofff** [comment]
Well, for any https website you do

openssl s_client -connect example.com:443 


and you get these public certificates. 

The private keys are encrypted as you can see.  I don’t know who’s complaining, but it does not really make sens. Tell him/her about asymmetrical cryptography 😉

**Comment by fubar2** [comment]
Good to know they're public. Gitguardian will probably continue to complain despite the stupidity. They probably just look for entropy in strings...
