### ISSUE TITLE
Could you allow FastQC to display images on Mississipi server?

### ISSUE THREAD

**Issue by slecrom** [ARTbio/galaxyXpand#43]
Dear ARTbio team,

I am testing my practical for students and the images from the FastQC tool are not display on the Mississipi server. Would it be possible to allow the tool to display images?

Thank you for your help.
Best
Stephane

**Comment by drosofff** [comment]
Ca c'est fait ! Check out please and confirm it works.

**Comment by slecrom** [comment]
Je viens de retourner sur la Webpage de FastQC mais la page html ne s'affiche pas. Je te mets la copie d'écran de ce que je vois.
![screenshot-mississippi sorbonne-universite fr-2023 10 25-12_19_02](https://github.com/ARTbio/galaxyXpand/assets/8030105/8691efca-04cb-4725-bed1-dcb8a81dad45)

**Comment by drosofff** [comment]
et si tu fais retourner l'outil ?

**Comment by slecrom** [comment]
Oui ça fonctionne quand je relance l'outil. Merci.
